services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: root_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network 

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=root_password
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - db
      - redis
    volumes:
      - ./wp:/var/www/html
    networks:
      - wordpress_network

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    restart: always
    expose:
      - '6379'
    volumes:
      - redis_data:/data
    networks:
      - wordpress_network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
volumes:
  db_data:
  redis_data:

networks:
  wordpress_network:
    driver: bridge